# Generated by Django 4.1.1 on 2022-10-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_Software_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisation_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
