# Generated by Django 4.1.1 on 2022-11-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_Software_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_book',
            name='first_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='organisation_email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
