# Generated by Django 4.1.1 on 2022-11-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_Software_App', '0003_alter_user_organisation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_book',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
    ]
