# Generated by Django 4.1.1 on 2022-11-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_Software_App', '0004_company_book_delete_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organisation_email',
        ),
    ]
