# Generated by Django 4.1.1 on 2022-11-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_Software_App', '0005_remove_user_organisation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_book',
            name='deleted_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
