# Generated by Django 4.1.1 on 2022-11-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_Software_App', '0006_alter_company_book_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_book',
            name='delete_status',
        ),
        migrations.AlterField(
            model_name='company_book',
            name='deleted_at',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
