# Generated by Django 4.1.1 on 2022-11-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_Software_App', '0007_remove_company_book_delete_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='deleted_at',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
