# Generated by Django 4.1.1 on 2022-11-17 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_Software_App', '0008_alter_organisation_deleted_at_alter_user_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tax_num', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('sale_price', models.CharField(default='', max_length=100)),
                ('purchase_price', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='Account_Software_App/images/%Y/%m/%d/')),
                ('enable', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_Software_App.company_book')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_Software_App.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
