# Generated by Django 4.1.1 on 2022-11-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_Software_App', '0009_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Picture',
            new_name='picture',
        ),
    ]
