# Generated by Django 4.1.1 on 2022-11-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_Software_App', '0010_module_type_rename_picture_items_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('enable', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.CharField(blank=True, max_length=100)),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_Software_App.module_type')),
            ],
        ),
    ]
