# Generated by Django 4.1.1 on 2022-11-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_Software_App', '0011_create_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Tax',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CD', 'Compound'), ('FD', 'Fixed'), ('IN', 'Inclusive'), ('NR', 'Normal'), ('WH', 'Withholding')], default='CD', max_length=2)),
                ('enable', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
