# Generated by Django 4.1.1 on 2022-11-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_Software_App', '0014_rename_tax_num_items_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='Account_Software_App/images/'),
        ),
    ]
