# Generated by Django 4.1.1 on 2022-11-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_Software_App', '0015_alter_items_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Account_Software_App/images/'),
        ),
    ]
