# Generated by Django 4.1.1 on 2022-11-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_Software_App', '0016_alter_items_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='picture',
            field=models.ImageField(default='', upload_to='Account_Software_App/images/'),
        ),
    ]
