# Generated by Django 4.1.1 on 2022-11-28 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_Software_App', '0017_alter_items_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_Software_App.create_category'),
        ),
        migrations.AlterField(
            model_name='items',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting_Software_App.create_tax'),
        ),
    ]
